### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by rosiisab**
Put in both images and edited with dummy text

### CODE REVIEW

**Comment by jabiggs13** [comment]
I went in and checked your images on your site and it looks like your image caption is being blocked by the website footer.  To fix this, go back into your site html and just add in at least 3 more paragraphs of that dummy latin text after the figure tags but before the <br> tag - easy fix.

Once you do that save, commit to master, and push origin.  You'll have to come in and CLOSE this pull request and then create a new one with those changes.  I know that you'll have text here later on, but I just want to make sure that your caption for your second image is appearing correctly and that the popover is correct.

Let me know if you have any questions

**Comment by rosiisab** [comment]
Hi! So I accidentally edited and pushed to master before pulling from the master to start, and now it’s saying I can’t merge. Is there anyway to fix this?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rosiisab** [comment]
Hi! So I accidentally edited and pushed to master before doing a pull like we’re supposed to at the start. Now it’s saying I can’t merge. Is there any way to fix this?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jabiggs13** [comment]
Is it not letting you push within your desktop client?  If so, best thing to do is to (within the desktop client), click on "Repository" from the nav bar, then click pull.  Once that's complete, you should be able to push your edits back up.  Let me know if you have any other issues.  

If you are and you're free in the next hour, I'll still be in LEADR for a bit so you could stop by and we could try and figure it out that way.

**Comment by jabiggs13** [comment]
What you might have to do is to create a new pull request but have it come from the msu-anthro master branch into yours, that way you have the most updated version, then try pull/push - I hope that makes sense?

**Comment by rosiisab** [comment]
No, it’s not letting me pull on the github website. It says that it cannot automatically merge

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jabiggs13** [comment]
I'm not in LEADR today but in my lab in Giltner Hall, room 408.  You're welcome to stop by here if you want.  I'll also go in really quick and see if I can delete what I think are the problem files so that you can merge from the master.  We've been having problems recently with github putting in dummy files that then creates merge issues.

I'll message you again after I see what's wrong with the files.

**Comment by rosiisab** [comment]
So is it all good? Or should I try is again later today before the deadline?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Pull request merged**
